module.exports = {
  products: [
    {
      _id: '1',
      name: 'Knight Bracelet',
      category: 'animal',
      image: '/images/pulsera (31).JPEG',
      price: 59,
      brand: 'Seven Pearls',
      rating: 4.5,
      numReviews: 10,
      description:'pulsera bonita',
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Demon',
      category: 'Sunshine',
      image: '/images/pulsera (33).JPEG',
      price: 70,
      brand: 'Seven Pearls',
      rating: 5,
      numReviews: 51,
      description:'pulsera bonita',
    },
    {
      _id: '3',
      name: 'Knight Bracelet',
      category: 'Animal',
      image: '/images/pulsera (2).JPEG',
      price: 59,
      brand: 'Seven Pearls',
      rating: 4,
      numReviews: 45,
      description:'pulsera bonita',
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'Knight Bracelet',
      category: 'Sunshine',
      image: '/images/pulsera (32).JPEG',
      price: 90,
      brand: 'Seven Pearls',
      rating: 2.5,
      numReviews: 198,
      description:'pulsera bonita',
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Knight Bracelet',
      category: 'Animal',
      image: '/images/pulsera (3).JPEG',
      price: 119,
      brand: 'Seven Pearls',
      rating: 3.5,
      numReviews: 89,
      description:'pulsera bonita',
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Fire Ball Bracelet',
      category: 'Animal',
      image: '/images/pulsera (31).JPEG',
      price: 119,
      brand: 'Seven Pearls',
      rating: 3.5,
      numReviews: 89,
      description:'pulsera bonita',
      countInStock: 6,
    },
    {
      _id: '7',
      name: 'Fire Ball Bracelet',
      category: 'Animal',
      image: '/images/pulsera (4).JPEG',
      price: 70,
      brand: 'Seven Pearls',
      rating: 5,
      description:'pulsera bonita',
      numReviews: 51,
    },
    {
      _id: '8',
      name: 'Fire Ball Bracelet',
      category: 'Shunshine',
      image: '/images/pulsera (30).JPEG',
      price: 59,
      brand: 'Seven Pearls',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '9',
      name: 'Coral Bracelet',
      category: 'Animal',
      image: '/images/pulsera (5).JPEG',
      price: 90,
      brand: 'Seven Pearls',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '10',
      name: 'Coral Bracelet',
      category: 'Shunsine',
      image: '/images/pulsera (29).JPEG',
      price: 119,
      brand: 'Seven Pearls',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '11',
      name: 'Jaguar Green Bracelet',
      category: 'Pants',
      image: '/images/pulsera (6).JPEG',
      price: 119,
      brand: 'Seven Pearls',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '12',
      name: 'Jaguar Green Bracelet',
      category: 'Pants',
      image: '/images/pulsera (29).JPEG',
      price: 85,
      brand: 'Seven Pearls',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
